import Head from 'next/head'
import '../styles/globals.css'
import styles from '../styles/Home.module.css'

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Face Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header_top}>
          <div className={styles.header_logo}>
              FACES
          </div>
          <div className={styles.header_button}>
            <button className={styles.gen_button}>generate new users</button>
          </div>
      </div>
      <Component {...pageProps} />
    </div>
  )
}

export default MyApp
